name: Deploy to DigitalOcean

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '18'

     - name: Install dependencies
       run: cd natetrystuff-web && npm install

     - name: Build Next.js app
       run: cd natetrystuff-web && ls && npm run build
       continue-on-error: true  # This will allow the workflow to continue even if this step fails
       env:
         SPRING_BOOT_URL: http://localhost:8080
         CODE_HELPER_URL: http://localhost:1234
         SSH_HOST: ${{ secrets.SSH_HOST }}
         SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

     - name: Add secrets to .env.production
       run: |
         echo '' >> natetrystuff-web/.env.production
         echo 'AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}' >> natetrystuff-web/.env.production
     - name: Setup SSH Known Hosts
       run: |
         mkdir -p ~/.ssh
         touch ~/.ssh/known_hosts
         ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

     - name: Setup SSH Agent
       uses: webfactory/ssh-agent@v0.5.3
       with:
           ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

     - name: Copy built files and configuration to server
       run: |
         scp -r natetrystuff-web/.next natetrystuff-web/.env.production natetrystuff-web/package.json ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/apps/natetrystuff-web/app/
         ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} "cd /apps/natetrystuff-web/app && npm install"

     - name: Restart Service
       run: ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} 'sudo systemctl restart natetrystuff-web.service'